version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "nix"
    directories:
      - "/"
      - "/dev-shell/*"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      nix-flake:
        patterns:
          - "*"
