{ ... }:

{
  imports = [
    ./awscli.nix
    ./bat.nix
    ./carapace.nix
    ./claude-code.nix
    ./codex.nix
    ./copilot.nix
    ./devspace.nix
    ./difftastic.nix
    ./docker.nix
    ./espanso.nix
    ./eza.nix
    ./fzf.nix
    ./gemini-cli.nix
    ./ghostty.nix
    ./git.nix
    ./github.nix
    ./gitlab.nix
    ./helix.nix
    ./helm.nix
    ./jjui.nix
    ./jujutsu.nix
    ./k9s.nix
    ./kubectl.nix
    ./lazygit.nix
    ./mergiraf.nix
    ./ollama.nix
    ./pueue.nix
    ./starship.nix
    ./telepresence.nix
    ./terraform.nix
    ./wireshark.nix
    ./zed.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
