{ ... }:

{
  imports = [
    ./awscli.nix
    ./bat.nix
    ./carapace.nix
    ./chatgpt.nix
    ./claude.nix
    ./codex.nix
    ./copilot.nix
    ./devcontainer.nix
    ./devspace.nix
    ./difftastic.nix
    ./discord.nix
    ./docker.nix
    ./espanso.nix
    ./eza.nix
    ./freecad.nix
    ./fzf.nix
    ./gemini-cli.nix
    ./ghostty.nix
    ./git.nix
    ./github.nix
    ./gitlab.nix
    ./helm.nix
    ./iamlive.nix
    ./insomnia.nix
    ./intellij.nix
    ./jira-cli.nix
    ./jjui.nix
    ./jujutsu.nix
    ./k9s.nix
    ./kubectl.nix
    ./lazygit.nix
    ./lima.nix
    ./logitech.nix
    ./mergiraf.nix
    ./neovim.nix
    ./ollama.nix
    ./pueue.nix
    ./qemu.nix
    ./retroarch.nix
    ./starship.nix
    ./steam.nix
    ./sweethome3d.nix
    ./teams.nix
    ./telegram.nix
    ./telepresence.nix
    ./terraform.nix
    ./utm.nix
    ./vacuum.nix
    ./vscode.nix
    ./wireshark.nix
    ./zed.nix
    ./zellij.nix
    ./zoom.nix
    ./zoxide.nix
  ];
}
